### ISSUE TITLE
Not all tokens return boolean from transfer function

### ISSUE THREAD

**Issue by ColonelJ** [matter-labs/atomic-swaps#3]
https://github.com/matter-labs/atomic-swaps/blob/132a5cc1dfb8de12b5734a6323c509986d4951ff/contracts/Rescuer.sol#L42

Some tokens e.g. USDT won't return a boolean value from their `transfer` function, so you can't use this method.

Instead you can use safeTransfer from OpenZeppelin https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol  Probably easiest to just copy the required contracts into this repo.

**Comment by ly0va** [comment]
Fixed using this less verbose method

https://github.com/matter-labs/zksync-dev/blob/9bdf914004767c0a0c571f1a075b732fc740ca58/contracts/contracts/Utils.sol#L24

**Comment by ColonelJ** [comment]
I can't view that link...  I think there's a slight issue that you attempt the `abi.decode` of `returnedValue` even if `callSuccess` is `false`?  It might not be a valid decode, in which case it will revert.  Probably not a big issue (because it will later revert anyway) but I thought it was worth mentioning, and it could be fixed.

**Comment by ColonelJ** [comment]
Apparently `abi.decode(returnedValue, (bool))` could only fail if `returnedValue` was less than 32 bytes (doesn't seem to matter if it's longer).  I believe a revert either has 0 bytes (already covered this case), or it's the 4 byte selector 0x08c379a0 (for "Error(string)" followed by an ABI encoded string (which is at least 64 bytes for offset and length), so there's no possibility for the `abi.decode` to fail.  So basically the code is fine as is, I think!

**Comment by ly0va** [comment]
Thanks for the feedback, @ColonelJ!
